const BASE=window.APP_DATA;
const STORAGE='materiales_sap_v1';
const state=loadState();
let cart=[];
const $=s=>document.querySelector(s);
const norm=s=>(s??'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE));return x&&x.materials?x:structuredClone(BASE)}catch{return structuredClone(BASE)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fillSelect(el,items,blank=false){const current=el.value;el.innerHTML=(blank?'<option value="">Todos</option>':'')+items.map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(items.includes(current))el.value=current}
function init(){
 fillSelect($('#destinatario'),state.supervisors); fillSelect($('#supervisor'),state.supervisors); fillSelect($('#unidadMovil'),state.units); fillSelect($('#movimiento'),state.movements);
 $('#destinatario').value=state.defaults.destinatario||state.supervisors[0]||''; $('#puestoDescarga').value=state.defaults.puestoDescarga||'';
 const units=[...new Set(state.materials.map(x=>x.unit).filter(Boolean))].sort(); fillSelect($('#unitFilter'),units,true);
 renderResults();renderCart();bind();renderAdmin();
}
function filtered(){const q=norm($('#searchInput').value);const unit=$('#unitFilter').value;return state.materials.filter(m=>{const hay=norm([m.code,m.description,...(m.aliases||[])].join(' '));return(!q||q.split(' ').every(w=>hay.includes(w)))&&(!unit||m.unit===unit)&&(!$('#priorityOnly').checked||m.priority==='P')}).slice(0,120)}
function renderResults(){const list=filtered();$('#resultCount').textContent=`${list.length} resultado${list.length===1?'':'s'}`;$('#results').innerHTML=list.length?list.map(m=>`<article class="result-card"><div><div class="result-code">${escapeHtml(m.code)} · ${escapeHtml(m.unit)}</div><div class="result-desc">${escapeHtml(m.description)}</div><div class="aliases">${(m.aliases||[]).map(a=>`<span class="alias">${escapeHtml(a)}</span>`).join('')}${m.priority==='P'?'<span class="alias">PRIORIDAD P</span>':''}</div></div><button class="add-btn" data-add="${m.code}">＋ Agregar</button></article>`).join(''):'<div class="empty">No se encontraron materiales. Prueba con otro alias, descripción o matrícula.</div>'}
function add(code){const m=state.materials.find(x=>x.code===code);if(!m)return;const existing=cart.find(x=>x.code===code);if(existing)existing.qty++;else cart.push({...m,qty:1});renderCart();flash('Material agregado al pedido.');}
function renderCart(){
 $('#cartCount').textContent=`${cart.length} material${cart.length===1?'':'es'}`;$('#emptyCart').style.display=cart.length?'none':'block';
 $('#cartBody').innerHTML=cart.map((m,i)=>`<tr><td><b>${escapeHtml(m.code)}</b></td><td>${escapeHtml(m.description)}</td><td class="qty"><input type="number" min="0.01" step="0.01" value="${m.qty}" data-qty="${i}"></td><td>${escapeHtml(m.unit)}</td><td><button class="remove" data-remove="${i}">Quitar</button></td></tr>`).join('');
}
function sapRows(){return cart.map(m=>({
 'MATRICULA':m.code,'DESCRIPCION':m.description,'C1':state.defaults.c1||'','CANT':m.qty,'UNIDAD':m.unit,'TP':state.defaults.tp||'L','C2':state.defaults.c2||'','C3':state.defaults.c3||'','ALIM':state.defaults.alim||'GG00','CE':state.defaults.ce||'1000','OPERACION':state.defaults.operacion||'0010','LOTE':state.defaults.lote||'LDA-000000','TIPO DE APROVISIONAMIENTO':state.defaults.tipoAprovisionamiento||'Reserva para orden','POS':state.defaults.pos||'0','DESTINATARIO':$('#destinatario').value,'PUESTO DE DESCARGA':$('#puestoDescarga').value,'UBICACION FINAL':$('#ubicacionFinal').value,'SUPERVISOR':$('#supervisor').value,'UNIDAD MOVIL':$('#unidadMovil').value,'MOVIMIENTO':$('#movimiento').value
}))}
function tsv(){const rows=sapRows();if(!rows.length)return'';const h=Object.keys(rows[0]);return[h.join('\t'),...rows.map(r=>h.map(k=>r[k]).join('\t'))].join('\n')}
function csv(){const rows=sapRows();if(!rows.length)return'';const h=Object.keys(rows[0]);const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return'\ufeff'+[h.map(esc).join(';'),...rows.map(r=>h.map(k=>esc(r[k])).join(';'))].join('\r\n')}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function exportExcel(){if(!cart.length)return flash('Agrega al menos un material.',true);const rows=sapRows(),headers=Object.keys(rows[0]);const meta=`<table><tr><th>DESTINATARIO</th><th>PUESTO DE DESCARGA</th><th>UBICACION FINAL</th><th>SUPERVISOR</th><th>UNIDAD</th><th>MOVIMIENTO</th></tr><tr><td>${escapeHtml($('#destinatario').value)}</td><td>${escapeHtml($('#puestoDescarga').value)}</td><td>${escapeHtml($('#ubicacionFinal').value)}</td><td>${escapeHtml($('#supervisor').value)}</td><td>${escapeHtml($('#unidadMovil').value)}</td><td>${escapeHtml($('#movimiento').value)}</td></tr></table><br>`;const table=`<table border="1"><thead><tr>${headers.map(h=>`<th style="background:#fff900">${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${headers.map(h=>`<td>${escapeHtml(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;const html=`<html><head><meta charset="UTF-8"></head><body><h3>PEDIDO DE MATERIALES</h3>${meta}${table}</body></html>`;download('\ufeff'+html,`Pedido_Materiales_${new Date().toISOString().slice(0,10)}.xls`,'application/vnd.ms-excel');flash('Excel generado con el formato SAP.');}
function flash(msg,error=false){const s=$('#status');s.textContent=msg;s.style.color=error?'#c62828':'#15803d';setTimeout(()=>s.textContent='',3500)}
function renderAdmin(){fillSelect($('#destinatario'),state.supervisors);fillSelect($('#supervisor'),state.supervisors);fillSelect($('#unidadMovil'),state.units);$('#supervisorList').innerHTML=state.supervisors.map((x,i)=>`<span class="chip">${escapeHtml(x)} <button data-del-sup="${i}">×</button></span>`).join('');$('#unitList').innerHTML=state.units.map((x,i)=>`<span class="chip">${escapeHtml(x)} <button data-del-unit="${i}">×</button></span>`).join('')}
function bind(){
 $('#searchInput').addEventListener('input',renderResults);$('#unitFilter').addEventListener('change',renderResults);$('#priorityOnly').addEventListener('change',renderResults);$('#clearSearch').onclick=()=>{$('#searchInput').value='';renderResults();$('#searchInput').focus()};
 $('#results').onclick=e=>{const b=e.target.closest('[data-add]');if(b)add(b.dataset.add)};
 $('#cartBody').addEventListener('input',e=>{if(e.target.dataset.qty!==undefined)cart[+e.target.dataset.qty].qty=Number(e.target.value)||0});$('#cartBody').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){cart.splice(+b.dataset.remove,1);renderCart()}};
 $('#copySap').onclick=async()=>{if(!cart.length)return flash('Agrega al menos un material.',true);try{await navigator.clipboard.writeText(tsv());flash('Tabla copiada. Puedes pegarla directamente en SAP o Excel.')}catch{const ta=document.createElement('textarea');ta.value=tsv();document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();flash('Tabla copiada.')}};
 $('#exportCsv').onclick=()=>cart.length?download(csv(),`Pedido_Materiales_${new Date().toISOString().slice(0,10)}.csv`,'text/csv;charset=utf-8'):flash('Agrega al menos un material.',true);$('#exportExcel').onclick=exportExcel;$('#clearCart').onclick=()=>{if(confirm('¿Limpiar todos los materiales seleccionados?')){cart=[];renderCart()}};
 const d=$('#configDialog');$('#btnConfig').onclick=()=>d.showModal();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabpage').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
 $('#addSupervisor').onclick=()=>{const v=$('#newSupervisor').value.trim().toUpperCase();if(v&&!state.supervisors.includes(v)){state.supervisors.push(v);save();renderAdmin();$('#newSupervisor').value=''}};$('#addUnit').onclick=()=>{const v=$('#newUnit').value.trim().toUpperCase();if(v&&!state.units.includes(v)){state.units.push(v);save();renderAdmin();$('#newUnit').value=''}};
 $('#supervisorList').onclick=e=>{const b=e.target.closest('[data-del-sup]');if(b){state.supervisors.splice(+b.dataset.delSup,1);save();renderAdmin()}};$('#unitList').onclick=e=>{const b=e.target.closest('[data-del-unit]');if(b){state.units.splice(+b.dataset.delUnit,1);save();renderAdmin()}};
 $('#addAlias').onclick=()=>{const c=$('#aliasCode').value.trim(),a=$('#aliasText').value.trim().toUpperCase(),m=state.materials.find(x=>x.code===c);const msg=$('#aliasMsg');if(!m){msg.textContent='No se encontró esa matrícula.';msg.style.color='#c62828';return}m.aliases=m.aliases||[];if(a&&!m.aliases.includes(a))m.aliases.push(a);save();renderResults();msg.textContent=`Alias agregado a ${c}.`;msg.style.color='#15803d';$('#aliasText').value=''};
 $('#resetData').onclick=()=>{if(confirm('¿Restablecer supervisores, unidades y alias originales?')){localStorage.removeItem(STORAGE);location.reload()}};
}
init();
