const BASE=window.APP_DATA;
const STORAGE='materiales_sap_v2';
const state=loadState();
let cart=[];
const $=s=>document.querySelector(s);
const norm=s=>(s??'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function cloneBase(){return JSON.parse(JSON.stringify(BASE))}
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE));return x&&x.materials?x:cloneBase()}catch{return cloneBase()}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fillSelect(el,items,blank=false){const current=el.value;el.innerHTML=(blank?'<option value="">Todas las unidades</option>':'')+items.map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(items.includes(current))el.value=current}
function init(){
 fillSelect($('#destinatario'),state.supervisors);fillSelect($('#supervisor'),state.supervisors);fillSelect($('#unidadMovil'),state.units);
 $('#destinatario').value=state.defaults.destinatario||state.supervisors[0]||'';
 const pd=String(state.defaults.puestoDescarga||'RECUPERO').toUpperCase();$('#puestoDescarga').value=pd==='REC'?'RECUPERO':pd==='PED'?'PEDIDO':pd==='DEV'?'DEVOLUCION':pd;
 $('#alim').value=['GG01','GG02'].includes(state.defaults.alim)?state.defaults.alim:'GG01';
 $('#ce').value=['1003','1004'].includes(String(state.defaults.ce))?String(state.defaults.ce):'1003';
 const units=[...new Set(state.materials.map(x=>x.unit).filter(Boolean))].sort();fillSelect($('#unitFilter'),units,true);
 renderResults();renderCart();bind();renderAdmin();
}
function filtered(){const q=norm($('#searchInput').value);const unit=$('#unitFilter').value;return state.materials.filter(m=>{const hay=norm([m.code,m.description,...(m.aliases||[])].join(' '));return(!q||q.split(' ').every(w=>hay.includes(w)))&&(!unit||m.unit===unit)&&(!$('#priorityOnly').checked||m.priority==='P')}).slice(0,150)}
function renderResults(){const list=filtered();$('#resultCount').textContent=`${list.length} resultado${list.length===1?'':'s'}`;$('#results').innerHTML=list.length?list.map(m=>`<article class="result-card"><div><div class="result-code">${escapeHtml(m.code)} · ${escapeHtml(m.unit)}</div><div class="result-desc">${escapeHtml(m.description)}</div><div class="aliases">${(m.aliases||[]).map(a=>`<span class="alias">${escapeHtml(a)}</span>`).join('')}${m.priority==='P'?'<span class="alias">PRIORIDAD P</span>':''}</div></div><button class="add-btn" data-add="${m.code}">＋ Agregar</button></article>`).join(''):'<div class="empty">No se encontraron materiales. Prueba con otro alias, descripción o matrícula.</div>'}
function add(code){const m=state.materials.find(x=>x.code===code);if(!m)return;const existing=cart.find(x=>x.code===code);if(!existing)cart.push({...m,qty:0,qtyEdited:false});renderCart();flash(existing?'El material ya estaba agregado.':'Material agregado. Edita la cantidad resaltada en amarillo.',!!existing)}
function renderCart(){
 $('#cartCount').textContent=`${cart.length} material${cart.length===1?'':'es'}`;$('#emptyCart').style.display=cart.length?'none':'block';
 $('#cartBody').innerHTML=cart.map((m,i)=>`<tr class="${m.qty>0?'row-ready':'row-pending'}"><td><b>${escapeHtml(m.code)}</b></td><td>${escapeHtml(m.description)}</td><td class="qty"><input class="qty-input ${m.qty>0?'qty-ready':'qty-pending'}" type="number" min="0" step="0.01" value="${m.qty}" data-qty="${i}" aria-label="Cantidad de ${escapeHtml(m.description)}"></td><td>${escapeHtml(m.unit)}</td><td><button class="remove" data-remove="${i}">Quitar</button></td></tr>`).join('');
}
function hasPendingQty(){return cart.some(m=>!(Number(m.qty)>0))}
function movementCode(){return({PEDIDO:'PED',RECUPERO:'REC',DEVOLUCION:'DEV'})[$('#puestoDescarga').value]||$('#puestoDescarga').value}
function sapRows(){return cart.map(m=>({'MATRICULA':m.code,'DESCRIPCION':m.description,'C1':state.defaults.c1||'','CANT':Number(m.qty)||0,'UNIDAD':m.unit,'TP':state.defaults.tp||'L','C2':state.defaults.c2||'','C3':state.defaults.c3||'','ALIM':$('#alim').value,'CE':$('#ce').value,'OPERACION':state.defaults.operacion||'0010','LOTE':state.defaults.lote||'LDA-000000','TIPO DE APROVISIONAMIENTO':state.defaults.tipoAprovisionamiento||'Reserva para orden','POS':state.defaults.pos||'0','DESTINATARIO':$('#destinatario').value,'PUESTO DE DESCARGA':$('#puestoDescarga').value,'UBICACION FINAL':$('#ubicacionFinal').value,'SUPERVISOR':$('#supervisor').value,'UNIDAD MOVIL':$('#unidadMovil').value,'MOVIMIENTO':movementCode()}))}
function tsv(){const rows=sapRows();if(!rows.length)return'';const h=Object.keys(rows[0]);return[h.join('\t'),...rows.map(r=>h.map(k=>r[k]).join('\t'))].join('\n')}
function csv(){const rows=sapRows();if(!rows.length)return'';const h=Object.keys(rows[0]);const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return'\ufeff'+[h.map(esc).join(';'),...rows.map(r=>h.map(k=>esc(r[k])).join(';'))].join('\r\n')}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function validateExport(){if(!cart.length){flash('Agrega al menos un material.',true);return false}if(hasPendingQty()){flash('Hay materiales con cantidad 0. Completa las cantidades amarillas antes de exportar.',true);return false}return true}
function exportExcel(){if(!validateExport())return;const rows=sapRows(),headers=Object.keys(rows[0]);const meta=`<table><tr><th>DESTINATARIO</th><th>PUESTO DE DESCARGA (MOVIMIENTO)</th><th>UBICACION FINAL</th><th>SUPERVISOR</th><th>UNIDAD</th><th>ALIM</th><th>CE</th></tr><tr><td>${escapeHtml($('#destinatario').value)}</td><td>${escapeHtml($('#puestoDescarga').value)}</td><td>${escapeHtml($('#ubicacionFinal').value)}</td><td>${escapeHtml($('#supervisor').value)}</td><td>${escapeHtml($('#unidadMovil').value)}</td><td>${escapeHtml($('#alim').value)}</td><td>${escapeHtml($('#ce').value)}</td></tr></table><br>`;const table=`<table border="1"><thead><tr>${headers.map(h=>`<th style="background:#fff900">${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${headers.map(h=>`<td>${escapeHtml(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;download('\ufeff'+`<html><head><meta charset="UTF-8"></head><body><h3>PEDIDO DE MATERIALES</h3>${meta}${table}</body></html>`,`Pedido_Materiales_${new Date().toISOString().slice(0,10)}.xls`,'application/vnd.ms-excel');flash('Excel generado con el formato SAP.')}
function flash(msg,error=false){const s=$('#status');s.textContent=msg;s.style.color=error?'#c62828':'#15803d';setTimeout(()=>s.textContent='',4500)}
function renderAdmin(){fillSelect($('#destinatario'),state.supervisors);fillSelect($('#supervisor'),state.supervisors);fillSelect($('#unidadMovil'),state.units);$('#supervisorList').innerHTML=state.supervisors.map((x,i)=>`<span class="chip">${escapeHtml(x)} <button data-del-sup="${i}">×</button></span>`).join('');$('#unitList').innerHTML=state.units.map((x,i)=>`<span class="chip">${escapeHtml(x)} <button data-del-unit="${i}">×</button></span>`).join('')}
function pick(row,names){const keys=Object.keys(row);const target=names.map(norm);const key=keys.find(k=>target.includes(norm(k)))||keys.find(k=>target.some(t=>norm(k).includes(t)));return key?row[key]:''}
function rowsToMaterials(rows,source='EXCEL'){
 const out=[];for(const row of rows){const code=String(pick(row,['MATRICULA','MATRÍCULA','CODIGO','CÓDIGO','SAP','MATERIAL'] )||'').replace(/\.0$/,'').trim();const description=String(pick(row,['DESCRIPCION','DESCRIPCIÓN','DENOMINACION','DENOMINACIÓN','MATERIAL DESCRIPCION'])||'').trim();if(!/^\d{5,}$/.test(code)||!description)continue;const unit=String(pick(row,['UNIDAD','UM','U.M.','UND'])||'UN').trim().toUpperCase();const priority=String(pick(row,['PRIORIDAD','P'])||'').trim().toUpperCase()==='P'?'P':'';const aliasRaw=pick(row,['ALIAS','NOMBRE COMUN','NOMBRE COMÚN','NOMBRE CAMPO','DESCRIPCION ALIAS']);const aliases=String(aliasRaw||'').split(/[;,|]/).map(x=>x.trim()).filter(Boolean);out.push({code,description,unit,aliases,priority,source})}return out
}
function mergeMaterials(imported,replace=false){
 if(replace)state.materials=[];const map=new Map(state.materials.map(m=>[m.code,m]));for(const m of imported){const old=map.get(m.code);if(old){old.description=m.description||old.description;old.unit=m.unit||old.unit;old.priority=m.priority||old.priority;old.aliases=[...new Set([...(old.aliases||[]),...(m.aliases||[])])]}else{state.materials.push(m);map.set(m.code,m)}}state.materials.sort((a,b)=>a.description.localeCompare(b.description,'es'));save();const units=[...new Set(state.materials.map(x=>x.unit).filter(Boolean))].sort();fillSelect($('#unitFilter'),units,true);renderResults();return imported.length
}
async function importExcel(){const file=$('#excelFile').files[0],msg=$('#importMsg');if(!file){msg.textContent='Selecciona un archivo.';msg.style.color='#c62828';return}try{let materials=[];if(file.name.toLowerCase().endsWith('.csv')){const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const headers=lines.shift().split(sep).map(x=>x.replace(/^"|"$/g,'').trim());const rows=lines.map(line=>{const vals=line.split(sep).map(x=>x.replace(/^"|"$/g,'').trim());return Object.fromEntries(headers.map((h,i)=>[h,vals[i]||'']))});materials=rowsToMaterials(rows,'CSV')}else{if(typeof XLSX==='undefined')throw new Error('No se pudo cargar el lector de Excel. Abre la página con conexión a internet o usa CSV.');const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});for(const name of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:'',raw:false});materials.push(...rowsToMaterials(rows,name))}}
 const unique=[...new Map(materials.map(m=>[m.code,m])).values()];if(!unique.length)throw new Error('No se encontraron filas válidas. Verifica que existan columnas de matrícula y descripción.');const count=mergeMaterials(unique,$('#importMode').value==='replace');msg.textContent=`Base actualizada: ${count} materiales leídos. Total actual: ${state.materials.length}.`;msg.style.color='#15803d'}catch(err){msg.textContent=err.message||'No se pudo leer el archivo.';msg.style.color='#c62828'}
}
function bind(){
 $('#searchInput').addEventListener('input',renderResults);$('#unitFilter').addEventListener('change',renderResults);$('#priorityOnly').addEventListener('change',renderResults);$('#clearSearch').onclick=()=>{$('#searchInput').value='';renderResults();$('#searchInput').focus()};
 $('#results').onclick=e=>{const b=e.target.closest('[data-add]');if(b)add(b.dataset.add)};
 $('#cartBody').addEventListener('input',e=>{if(e.target.dataset.qty!==undefined){const i=+e.target.dataset.qty;cart[i].qty=Math.max(0,Number(e.target.value)||0);cart[i].qtyEdited=true;e.target.classList.toggle('qty-ready',cart[i].qty>0);e.target.classList.toggle('qty-pending',!(cart[i].qty>0));e.target.closest('tr').className=cart[i].qty>0?'row-ready':'row-pending'}});$('#cartBody').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){cart.splice(+b.dataset.remove,1);renderCart()}};
 $('#copySap').onclick=async()=>{if(!validateExport())return;try{await navigator.clipboard.writeText(tsv());flash('Tabla copiada. Puedes pegarla directamente en SAP o Excel.')}catch{const ta=document.createElement('textarea');ta.value=tsv();document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();flash('Tabla copiada.')}};
 $('#exportCsv').onclick=()=>validateExport()&&download(csv(),`Pedido_Materiales_${new Date().toISOString().slice(0,10)}.csv`,'text/csv;charset=utf-8');$('#exportExcel').onclick=exportExcel;$('#clearCart').onclick=()=>{if(confirm('¿Limpiar todos los materiales seleccionados?')){cart=[];renderCart()}};
 ['puestoDescarga','alim','ce'].forEach(id=>$('#'+id).addEventListener('change',()=>{state.defaults[id==="puestoDescarga"?'puestoDescarga':id]=$('#'+id).value;save()}));
 const d=$('#configDialog');$('#btnConfig').onclick=()=>d.showModal();document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabpage').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
 $('#addSupervisor').onclick=()=>{const v=$('#newSupervisor').value.trim().toUpperCase();if(v&&!state.supervisors.includes(v)){state.supervisors.push(v);save();renderAdmin();$('#newSupervisor').value=''}};$('#addUnit').onclick=()=>{const v=$('#newUnit').value.trim().toUpperCase();if(v&&!state.units.includes(v)){state.units.push(v);save();renderAdmin();$('#newUnit').value=''}};
 $('#supervisorList').onclick=e=>{const b=e.target.closest('[data-del-sup]');if(b){state.supervisors.splice(+b.dataset.delSup,1);save();renderAdmin()}};$('#unitList').onclick=e=>{const b=e.target.closest('[data-del-unit]');if(b){state.units.splice(+b.dataset.delUnit,1);save();renderAdmin()}};
 $('#addAlias').onclick=()=>{const c=$('#aliasCode').value.trim(),a=$('#aliasText').value.trim().toUpperCase(),m=state.materials.find(x=>x.code===c);const msg=$('#aliasMsg');if(!m){msg.textContent='No se encontró esa matrícula.';msg.style.color='#c62828';return}m.aliases=m.aliases||[];if(a&&!m.aliases.includes(a))m.aliases.push(a);save();renderResults();msg.textContent=`Alias agregado a ${c}.`;msg.style.color='#15803d';$('#aliasText').value=''};
 $('#importExcel').onclick=importExcel;
 $('#resetData').onclick=()=>{if(confirm('¿Restablecer la base, supervisores, unidades y alias originales?')){localStorage.removeItem(STORAGE);location.reload()}};
}
init();
